### PR TITLE
[browser] set browserInit async

### LINKED ISSUE #1068: [Browser] browserInit() doesn't wait for the sdk to be loaded
I think that browserInit() should be async. We should wait for the sdk to be loaded with 
window.fbAsyncInit = function() {. So we should add a callback to this method.

### PR DESCRIPTION
**Pull request by oliviertassinari**
Fix #1068.
- Replace tabs by space in the README.md
- Add js to format the code in the README.md
- Update README.md with the new API

### CODE REVIEW

**Comment by agustinhaller** [comment]
why don't you merge this fixes?

**Comment by oliviertassinari** [comment]
@aogilvie do you want me to rebase?

**Comment by aogilvie** [comment]
Yeah please mate. Also PR to develop branch of you could be so kind. Cheers.

**Comment by oliviertassinari** [comment]
@aogilvie Done

**Pull request closed without merging**
