### PR TITLE
auth_type: 'rerequest' support

### PR DESCRIPTION
**Pull request by robotvert**
Addresses issues #837 and #642 

add 'rerequest' to the permissions array to re-ask for declined permissions, for instance:

```javascript
// first call
facebookConnectPlugin.login(['email'], ....)

// after the user declined the email permission, to retry:
facebookConnectPlugin.login(['email', 'rerequest'], ....)
```

see [the facebook docs](https://developers.facebook.com/docs/facebook-login/login-flow-for-web/v2.3#re-asking-declined-permissions) for the proper way to use this great power which of course comes with great responsibility.

not too happy about the mixing of permissions and auth_type but it keeps the whole thing simple and backward compatible this way.

### CODE REVIEW

**Comment by aogilvie** [comment]
Thanks a lot!

**Comment by robotvert** [comment]
Note that you might want to update the README to mention this when it's in master.
Totally skipped that part, sorry :bow:

**Comment by aogilvie** [comment]
:+1:

**Comment by ilyakar** [comment]
Exactly what I need! When is this going to be in the master? How stable is the current development branch to use in a project?

**Comment by mrhwangmiyoung** [comment]
I tried this but the fb plugin displays "Invalid Scope: Rerequest". Any ideas how to fix?

**Comment by ilyakar** [comment]
Yup. It’s not fixed at all. It has only been fixed for the browser, iOS has not been updated, not sure about Android.

**Comment by robotvert** [comment]
it's only for the web flow AFAIK and you must append this scope *only* after the user declined some of the permissions you asked, going like:
```
asking perms
↓
user declines some
↓
app gets control again, notices some perms are missing.
↓
app shows dialog saying why it needs those perms
↓
app does another FB auth request but with the "rerequest" scope
↓
user faces the perms screen again
```

**Comment by ilyakar** [comment]
I tried appending this scope for every request even before the permissions have been declined. Maybe it's not such a bad idea to have the rerequest authorisation type a default one?

**Comment by robotvert** [comment]
This is not how you use this feature. 
Read the [FB docs](https://developers.facebook.com/docs/facebook-login/login-flow-for-web/v2.3).
The "rerequest" scope is to be used **only after** the user declined permissions, to let you retry obtaining them.

**Comment by robotvert** [comment]
I don't know what you mean by Android and iOS is needed, in my ionic/cordova app it works like a charm on real devices. Android and iOS SDK are different beasts made for you when you're coding full native apps, which is not what phonegap/cordova apps are.

**Comment by mrhwangmiyoung** [comment]
can you share a snippet of your code? @robotvert

**Comment by robotvert** [comment]
```javascript
var permissions = ['email'];
if ($scope.rerequest === true) { permissions.push('rerequest'); }
$cordovaFacebook.login(permissions).then(success, failure);
```

**Comment by ilyakar** [comment]
@robotvert are you using the dev version? As far as I understand the native plugin code has to be updated too. Dev it works on my browser, iOS doesn't work.

**Comment by mrhwangmiyoung** [comment]
oh you are using ionic. I am yet to use that framework since I barely know anything on AngularJS. Do you know how to implement it in pure JavaScript?

**Comment by robotvert** [comment]
@ilyakar using the `develop` branch if this is what you meant. The plugin has native components for whatever platform you're targeting and it's fetching the web SDK from FB directly.

@mrhwangmiyoung the snippet above is pure javascript, the only ionic part is the `$cordovaFacebook` wrapper provided by the [ngCordova plugin](http://ngcordova.com/docs/plugins/facebook/). How you deal with saving the state between attempts depends on you're app, here in Angular I'm simply putting that in the `$scope`.

**Comment by seblau** [comment]
Still **not working** here (Ionic Framework & iOS) despite a checked out `develop`-branch.

The Facebook Login redirects me to the following URL:
`https://m.facebook.com/v2.2/dialog/oauth?sdk_version=3.21.1& [...] &scope=email,user_birthday,user_events,rerequest [...]`

The **rerequest** should definitely not appear in the `scope`-parameter in the url. It should rather be a separate url field like: `auth_type=rerequest`.

@robotvert: Your new `login`-function is responsible for extracting the `rerequest`from the permissions list into an own url field. Unfortunately, for some reason it shows no effect, because the `rerequest`-permission entry gets handled like a permission and is not extracted from the list by the login function.

        // Attach this to a UI element, this requires user interaction.
        login: function (permissions, s, f) {
            // JS SDK takes an object here but the native SDKs use array.
            var options = {};
            if (permissions && permissions.length > 0) {
                var index = permissions.indexOf('rerequest');
                if (index > -1) {
                    permissions.splice(index, 1);
                    options.auth_type = 'rerequest';
                }
                options.scope = permissions.toString();
            }
            
            FB.login(function (response) {
                if (response.authResponse) {
                    s(response);
                } else {
                    f(response.status);
                }
            }, options);
        },

Does anyone have a plane why this is the way it is?

**Comment by robotvert** [comment]
@seblau Are you sure you switched branches properly? It really looks like the old branch behavior, eg, grab the given permissions and send them "as is".

Also, I don't know what devices you're using but the piece of code you quoted **does** work here, to make sure here's what I just did in the JS console:

```javascript
var permissions = ['email', 'user_birthday', 'user_events', 'rerequest'];
// => undefined
var options = {};
// => undefined

if (permissions && permissions.length > 0) {
  var index = permissions.indexOf('rerequest');
  if (index > -1) {
    permissions.splice(index, 1);
    options.auth_type = 'rerequest';
  }
  options.scope = permissions.toString();
}
// => "email,user_birthday,user_events"

options
// => Object {auth_type: "rerequest", scope: "email,user_birthday,user_events"}
```

Anyway I'm not working on the project that had me add this feature in the first place so I can't do much more.

**Comment by seblau** [comment]
@robotvert Your suggestion is right that this login function gets not called in my case, because it only gets called:

    if (cordova.platformId == "browser") { ...

and my platform is not the **browser**, but **iOS**.

In case of **iOS**, the following is called: (which I suspect refers to the `FacebookConnectPlugin.m`-class in `/platforms/ios/HelloCordova/Plugins/com.phonegap.plugins.facebookconnect/`)

    var exec = require("cordova/exec");
    login: function (permissions, s, f) {
            exec(s, f, "FacebookConnectPlugin", "login", permissions);
    }

So the question is, 
* Does anyone know if the `login`-function inside the `FacebookConnectPlugin.m` can handle the `auth_type=rerequest` appropriately? 

According to my latest observations it can't. That would mean that the `login`-function inside `FacebookConnectPlugin.m` needs the to be adapted in order the support the `auth_type=rerquest` for iOS.

**Pull request merged**
