### PR TITLE
Add tests for phonegap-facebook-plugin

### PR DESCRIPTION
**Pull request by dnoliver**
Hello :)

I am Nicolas Oliver, from Intel® XDK Development Team.
As you may know, the phonegap-facebook-plugin  is listed as a one of the Featured Cordova Plugins provided by the Intel® XDK, allowing users to download and use the plugin in their apps.
In an effort to increase the testability, we have decided to do a source code contribution.  
Using the Cordoba Plugin Test Framework, provided by Apache, I have developed some test suites for the phonegap-facebook-plugin.
Those tests suites can be executed using the Cordova Mobile Spec app, or using the process described in the standard Cordova Plugin Test Framework for running tests.

Here are some screenshots of the tests executions

screenshot_2015-04-22-14-56-40 1

screenshot_2015-04-22-14-56-47 1

### CODE REVIEW

**Comment by ronkorving** [comment]
Hi @dnoliver,

Thanks for your awesome contribution. Do you think it would be possible to add TravisCI integration to this?

**Comment by aogilvie** [comment]
Thanks. We should add to the CONTRIBUTING.md how to run the tests (this can be a separate PR).

**Comment by dnoliver** [comment]
Hi @ronkorving, 

I have never use  TravisCI (I do use Teamcity a lot for CI), so I don't know if the TravisCI infrastructure support running Cordova Plugin tests, and I don't know how it could read the tests results. Also, the app need a little human interaction to run the the automatic tests. Maybe, I could check in any of the core Cordova plugin, and see if they have integrated their tests in TravisCI

**Comment by ronkorving** [comment]
@dnoliver That would be cool. Any way we can automatically CI test this would be a real benefit for future contributions.

**Comment by dnoliver** [comment]
Well, this is what I found: 

There is some level of continuous testing in core plugins. They use cordova-paramedic https://github.com/purplecabbage/cordova-paramedic, something I was not aware of. In the little documentation, it clarifies that only works in IOS (maybe android support will be in place in the future)

Here is an issue to integrates all core plugins tests into TravisCI using cordova-paramedics. 

here is the .travis.yml that cordova-plugin-file use:
```
language: objective-c
git:
  depth: 2
node_js:
  - "0.10"
install:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config 
  - cd ..
  - npm install -g cordova-paramedic
  - npm install -g cordova
  - npm install -g ios-sim
script:
  - cordova-paramedic --platform ios --plugin ${TRAVIS_BUILD_DIR} 
```

**Pull request merged**
