### PR TITLE
Cordova 5.0.0 Multiple Dex Issue

### PR DESCRIPTION
**Pull request by eatsjobs**
This resolve the issue reported here [http://forum.ionicframework.com/t/reporting-bug-crosswalk-issue-with-other-plugins/18028]

### CODE REVIEW

**Comment by kaansoral** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.android.support:support-v4:[21,22).
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
         https://repo1.maven.org/maven2/com/android/support/support-v4/
     Required by:
         :android:unspecified > com.facebook.android:facebook-android-sdk:3.23.0

I've tried your solution, this was the result, how do you solve the v4 dependency?

**Comment by eatsjobs** [comment]
Can you please try to add this and let me know? <framework src="com.android.support:support-v4:21.0.0" />. Delete the android.support.v4 from your plugin if there's one.

**Comment by kaansoral** [comment]
* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find com.android.support:support-v4:21.0.0.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/21.0.0/support-v4-21.0.0.pom
         https://repo1.maven.org/maven2/com/android/support/support-v4/21.0.0/support-v4-21.0.0.jar
     Required by:
         :android:unspecified
   > Could not find any version that matches com.android.support:support-v4:[21,22).
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
         https://repo1.maven.org/maven2/com/android/support/support-v4/
     Required by:
         :android:unspecified > com.facebook.android:facebook-android-sdk:3.23.0

Tested on a clean build, this is the result

**Comment by eatsjobs** [comment]
```
cordova platform add android && cordova build android
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.buongiorno.firewater
	Name: Firewater
	Activity: MainActivity
	Android target: android-22
Copying template files...
Android project created with cordova-android@4.0.0
Discovered plugin "cordova-plugin-whitelist" in config.xml. Installing to the project
Fetching plugin "cordova-plugin-whitelist@1" via npm
npm http GET https://registry.npmjs.org/cordova-plugin-whitelist
npm http 304 https://registry.npmjs.org/cordova-plugin-whitelist
Installing "cordova-plugin-whitelist" for android
Installing "com.phonegap.plugins.facebookconnect" for android
Running command: /home/pasquale/projects/hybrid/game/games/firewater/platforms/android/cordova/build 
ANDROID_HOME=/home/pasquale/Android/Sdk
JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
Running: /home/pasquale/projects/hybrid/game/games/firewater/platforms/android/gradlew cdvBuildDebug -b /home/pasquale/projects/hybrid/game/games/firewater/platforms/android/build.gradle -Dorg.gradle.daemon=true
:preBuild
:compileDebugNdk
:preDebugBuild
:checkDebugManifest
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugBuildConfig
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar
:CordovaLib:compileDebugNdk
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug
:prepareAndroidCordovaLibUnspecifiedDebugLibrary
:preReleaseBuild
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:preReleaseBuild
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:compileReleaseJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:packageReleaseJar
:CordovaLib:compileReleaseNdk
:CordovaLib:packageReleaseJniLibs UP-TO-DATE
:CordovaLib:packageReleaseLocalJar UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:bundleRelease
:prepareComAndroidSupportSupportV42103Library
:prepareComFacebookAndroidFacebookAndroidSdk3230Library
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResources
:generateDebugSources
:compileDebugJava
:preDexDebug
:dexDebug
:processDebugJavaRes UP-TO-DATE
:validateDebugSigning
:packageDebug
:zipalignDebug
:assembleDebug
:cdvBuildDebug

BUILD SUCCESSFUL

Total time: 34.329 secs
Built the following apk(s):
    /home/pasquale/projects/hybrid/game/games/firewater/platforms/android/build/outputs/apk/android-debug.apk
```
Me too. This is my output after i've created a new project and cloned the plugins from the fork of the repo. i've only this plugin installed.

**Comment by kaansoral** [comment]
Could it be a linux/osx build difference?
I'm using osx

**Comment by eatsjobs** [comment]
Mmm i don't know try to write your configuration.
Mine is:
- cordova 5.0.0
- npm 2.10.1
- node v0.12.4

**Comment by kaansoral** [comment]
I'm also using the latest cordova, and my android-sdk is also pretty up to date

I'm going to try installing more components through "Android SDK Manager" yet I don't think it will help

I have a hunch installing the local google support library maven repository from the "Extras" section might solve the issue

In any case, even if it works, this fix will probably not work for everyone

**Comment by kaansoral** [comment]
Well downloading the library collection manually fixed the issue I linked, however the original error returned

You should add this plugin: https://github.com/phonegap-build/PushPlugin and test your fix again

The main issue is the V4 of the fb plugin clashing with the V13 of the push plugin
Which results in: "com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;"

**Comment by mircoc** [comment]
hi @kaansoral,

try to change in plugin.xml of PushPlugin this:
<source-file src="src/android/libs/gcm.jar" target-dir="libs/" />
with:
<framework src="com.google.android.gms:play-services-gcm:+" />

and remove this:
<source-file src="src/android/com/plugin/android-support-v13.jar" target-dir="libs/" />

let me know

**Comment by kaansoral** [comment]
I discovered that I was actually using this version of the PushPlugin: https://github.com/Telerik-Verified-Plugins/PushNotification (Eddy's forks are always more refined/updated/bug-free, I've tested the original plugin too a while ago, the behaviour was the same)

I've tested various things, various library options, yet the clash always remains

I've removed the v13 of the telerik version of the PushPlugin too, yet the results was the same, the two plugins doesn't blend

In the meantime, I also installed all the repositories from the Android SDK, they shifted the errors/behaviours, yet the result remains the same, each plugin works and compiles well on it's own, yet they can't be combined

I'm continuing my experiments, I might try exactly what you suggested too, I will let you guys know If I get any results
(Without the V13, the telerik version of the pushplugin can't find the .setColor of the Builder - that was the issue as far as I recall)

**Comment by jtomaszewski** [comment]
Related to:

https://github.com/Wizcorp/phonegap-facebook-plugin/issues/1028
https://github.com/Wizcorp/phonegap-facebook-plugin/issues/750
https://github.com/Wizcorp/phonegap-facebook-plugin/issues/992

My solution: 
- remove all `android-support-v13.jar` and `android-support-v4.jar` files (in all the plugins: like [phonegap-facebook-plugin](https://github.com/Wizcorp/phonegap-facebook-plugin), [PushNotification](https://github.com/Telerik-Verified-Plugins/PushNotification), [cordova-plugin-local-notifications](https://github.com/katzer/cordova-plugin-local-notifications))
- remove all references that include them as dependencies, like `<source-file src="src/android/com/plugin/android-support-v13.jar" target-dir="libs/" />` and similar ones

Currently I use in my app all of those 3 plugins written above at once, and it works okay. =)

**Comment by sgrebnov** [comment]
I like this patch but this is CLI 5.0+/ Android 4.0+/Gradle only.

Below is alternative fix which allows using Ant and support CLI 4.3.0+
https://github.com/Wizcorp/phonegap-facebook-plugin/pull/1032

Similar fix must be applied to PushPlugin. This won't work until both plugins will use gradle to specify dependencies instead of jars in libs folder.

**Comment by poocart** [comment]
removed `<source-file src="src/android/com/plugin/android-support-v13.jar" target-dir="libs/" />` from PushPlugin and now it works, thanks @mircoc

**Comment by muditjaju** [comment]
Just tested and it works perfect, saving from a lot of Multiple Dex files error
and also is a lot more manageable

**Comment by aogilvie** [comment]
Closing in favour of https://github.com/Wizcorp/phonegap-facebook-plugin/pull/1032

**Comment by vyarmak** [comment]
Had similar problem with Facebook Connect and LocalNotification

**com.phonegap.plugins.facebookconnect 0.11.0 "Facebook Connect"**
**de.appplant.cordova.plugin.local-notification 0.8.2-dev "LocalNotification"**

de.appplant.cordova.plugin.local-notification - will install cordova-plugin-android-support-v4 that will cause Dex issue.

Fix was quite simple (after a couple of hours :) :

plugins/com.phonegap.plugins.facebookconnect/plugin.xml:

```
-	<framework src="platforms/android/FacebookLib" custom="true" />
+	<framework src="com.android.support:support-v4:+" />
+	<framework src="com.facebook.android:facebook-android-sdk:3.23.0" />
```

plugins/de.appplant.cordova.plugin.local-notification/plugin.xml:

```
-	<dependency id="cordova-plugin-android-support-v4" />
+	<framework src="com.android.support:support-v4:+" />
```

Hope this will help someone.

**Comment by sgrebnov** [comment]
@vyarmak I think this is the right way to move forward, we should not keep Facebook sdk source code; we should rely on  on `com.facebook.android:facebook-android-sdk` instead - I'll start discussion to make this change

**Comment by silveirado** [comment]
@vyarmak Great! that's work for me. Pls send your pull request to https://github.com/Telerik-Verified-Plugins/Facebook, because this is most active fork. Tx a lot!

**Comment by 0x1ad2** [comment]
@silveirado thanks for the url! Fixed all my issues by installing the fork:

`cordova plugin add https://github.com/Telerik-Verified-Plugins/Facebook.git --variable APP_ID="your-facebook-id" --variable APP_NAME="your-facebook-app-name"`

**Pull request closed without merging**
