### PR TITLE
Getapplicationsignature

### PR DESCRIPTION
**Pull request by EddyVerbruggen**

### CODE REVIEW

**Comment by aogilvie** [comment]
@EddyVerbruggen I don't see this as a valid API feature. It's also only required in development, or is there some other use-case? Lastly, this is Android-only, we try to make the APIs as cross-platform as possible, it may mislead some developers as much as help some others.

**Comment by EddyVerbruggen** [comment]
It's exactly that: a convenience method for Android dev, pointer at from the docs. You need it for every app using the plugin and I found it way easier than the alternative. But it's your call and I'll leave it as is in my fork. 

Cheers,
Eddy

**Comment by kaansoral** [comment]
If this method is also added to the readme, it should eliminate a lot of beginner issues in the long run, otherwise most people start a "how do I generate the signature" issue

I also think this should definitely be kept

**Comment by EddyVerbruggen** [comment]
The PR contains a readme update :)

**Pull request merged**
